language: go

matrix:
  include:
    - os: linux
      go: 1.9
    - os: linux
      go: tip
    - os: osx
      osx_image: xcode8.3
      go: 1.9
    - os: osx
      osx_image: xcode8.3
      go: tip

script:
  - go vet -v ./...
  - make test
  # we must update docs manually by `make update-doc`
  # (fail if changes are detected)
  - make update-doc
  - git diff --exit-code

notifications:
  email:
    # we can see the result on GitHub :)
    on_success: never
    # notify only first failure
    on_failure: change
